name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Set up basic system
        run: |
          echo "::group::Update system"
          pacman -Syu --noconfirm
          echo "::endgroup::"

          echo "::group::Install basic packages"
          pacman -S --noconfirm --needed git base-devel
          echo "::endgroup::"

          echo "::group::Add non-privileged user to run makepkg"
          useradd -m build
          echo "build ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
          echo "::endgroup::"
      - name: Install dependencies for mommy
        run: |
          echo "::group::Install man-db"
          pacman -S --noconfirm man-db
          sed -i "/NoExtract.*man/d" /etc/pacman.conf  # Extract man pages
          echo "::endgroup::"

          echo "::group::Install ShellSpec"
          git clone https://aur.archlinux.org/shellspec-bin.git
          chown -R build:build ./shellspec-bin
          cd ./shellspec-bin
          sudo -u build makepkg -si --noconfirm
          cd -
          echo "::endgroup::"

          echo "::group::Install additional shells"
          pacman -S --noconfirm fish zsh
          echo "::endgroup::"
      - name: Checkout mommy
        uses: actions/checkout@v4
        with:
          repository: FWDekker/mommy
          path: mommy
          ref: main
      - name: Fix mommy directory ownership
        run: chown -R build:build ./mommy/

      - name: Checkout aur-mommy
        uses: actions/checkout@v4
        with:
          path: aur-mommy
      - name: Fix aur-mommy directory ownership
        run: chown -R build:build ./aur-mommy/
      - name: Test AUR package
        run: |
          cd ./aur-mommy/

          echo "::group::Patch"
          sudo -u build ./update.sh dev
          echo "::endgroup::"

          echo "::group::Build and install"
          sudo -u build makepkg -si --noconfirm
          echo "::endgroup::"

          cd ../mommy/

          echo "::group::Test"
          make system=1 test
          echo "::endgroup::"

          echo "::group::Uninstall"
          pacman -R --noconfirm mommy
          echo "::endgroup::"
